services:
  web:
    build: ./src
    ports:
      - 8080:8080
  flagd:
    image: ghcr.io/open-feature/flagd:latest
    container_name: flagd
    command: start --uri https://raw.githubusercontent.com/Inx51/flagd-lab/refs/heads/master/flags.json
    ports:
      - 8013:8013